In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies.shape

(4803, 20)

In [7]:
credits.shape

(4803, 4)

In [8]:
movie = movies.merge(credits , on='title')

In [9]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movie.shape

(4809, 23)

In [11]:
movies = movie[['id','genres','keywords','title','overview','cast','crew']]

In [12]:
movies

,id,genres,keywords,title,overview,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,559,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,38757,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...","[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",Tangled,When the kingdom's most wanted-and most charmi...,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,99861,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,767,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...","[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,209112,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."
10,1452,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...",Superman Returns,Superman returns to discover his 5-year absenc...,"[{""cast_id"": 3, ""character"": ""Superman / Clark...","[{""credit_id"": ""553bef6a9251416874003c8f"", ""de..."
11,10764,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",Quantum of Solace,Quantum of Solace continues the adventures of ...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe43b29251416c7501aa63"", ""de..."
12,58,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,"[{""cast_id"": 37, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""52fe4211c3a36847f8001873"", ""de..."
13,57201,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,"[{""cast_id"": 4, ""character"": ""Tonto"", ""credit_...","[{""credit_id"": ""52fe4928c3a36847f818be95"", ""de..."
14,49521,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...",Man of Steel,A young boy learns that he has extraordinary p...,"[{""cast_id"": 2, ""character"": ""Clark Kent / Kal...","[{""credit_id"": ""52fe4799c3a36847f813e667"", ""de..."
15,2454,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,"[{""cast_id"": 1, ""character"": ""Prince Caspian"",...","[{""credit_id"": ""55a239e69251412979002e8b"", ""de..."
16,24428,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",The Avengers,When an unexpected enemy emerges and threatens...,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""52fe4495c3a368484e02b1cf"", ""de..."
17,1865,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,"[{""cast_id"": 15, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""566b4f54c3a3683f56005151"", ""de..."
18,41154,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...","[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,"[{""cast_id"": 4, ""character"": ""Agent J"", ""credi...","[{""credit_id"": ""52fe45b7c3a36847f80d68c7"", ""de..."
19,122917,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,"[{""cast_id"": 10, ""character"": ""Bilbo Baggins"",...","[{""credit_id"": ""548ad49a9251414fa20011ab"", ""de..."
20,1930,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,"[{""cast_id"": 56, ""character"": ""Peter Parker / ...","[{""credit_id"": ""5395a60dc3a368641d004492"", ""de..."
21,20662,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",Robin Hood,When soldier Robin happens upon the dying Robe...,"[{""cast_id"": 1, ""character"": ""Robin Longstride...","[{""credit_id"": ""52fe43f2c3a368484e0076ad"", ""de..."
22,57158,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...","[{""cast_id"": 3, ""character"": ""Bilbo Baggins"", ...","[{""credit_id"": ""52fe4926c3a36847f818b787"", ""de..."
23,2268,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",The Golden Compass,"After overhearing a shocking secret, precociou...","[{""cast_id"": 43, ""character"": ""Lyra Belacqua"",...","[{""credit_id"": ""52fe4348c3a36847f8048635"", ""de..."
24,254,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...","[{""id"": 774, ""name"": ""film business""}, {""id"": ...",King Kong,"In 1933 New York, an overly ambitious movie pr...","[{""cast_id"": 5, ""character"": ""Ann Darrow"", ""cr...","[{""credit_id"": ""52fe422ec3a36847f800a1d7"", ""de..."
25,597,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",Titanic,"84 years later, a 101-year-old woman named Ros...","[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...","[{""credit_id"": ""52fe425ac3a36847f8017985"", ""de..."
26,271110,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",Captain America: Civil War,"Following the events of Age of Ultron, the col...","[{""cast_id"": 9, ""character"": ""Steve Rogers / C...","[{""credit_id"": ""569443d59251414b67000428"", ""de..."
27,44833,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...","[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",Battleship,"When mankind beams a radio signal into space, ...","[{""cast_id"": 3, ""character"": ""Lieutenant Alex ...","[{""credit_id"": ""52fe469ec3a36847f8108d45"", ""de..."
28,135397,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",Jurassic World,Twenty-two years after the events of Jurassic ...,"[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...","[{""credit_id"": ""52fe4bf7c3a368484e1a0683"", ""de..."
29,37724,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",Skyfall,When Bond's latest assignment goes gravely wro...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe46689251416c910537ad"", ""de..."
...,...,...,...,...,...,...,...
4779,2292,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 1361, ""name"": ""salesclerk""}, {""id"": 30...",Clerks,Convenience and video store clerks Dante and R...,"[{""cast_id"": 7, ""character"": ""Dante Hicks"", ""c...","[{""credit_id"": ""52fe434ac3a36847f8049253"", ""de..."
4780,42497,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 1566, ""name"": ""dream""}, {""id"": 13059, ...",Pink Narcissus,An erotic poem set in the fantasies of a young...,"[{""cast_id"": 1006, ""character"": ""Pan"", ""credit...","[{""credit_id"": ""52fe4606c3a36847f80e7ed9"", ""de..."
4781,33693,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...","[{""id"": 171993, ""name"": ""mumblecore""}]",Funny Ha Ha,"Unsure of what to do next, 23-year-old Marnie ...","[{""cast_id"": 1, ""character"": ""Marnie"", ""credit...","[{""credit_id"": ""52fe45309251416c9102a535"", ""de..."
4782,14585,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 1438, ""name"": ""office""}, {""id"": 9673, ...",In the Company of Men,Two business executives--one an avowed misogyn...,"[{""cast_id"": 1, ""character"": ""Chad"", ""credit_i...","[{""credit_id"": ""52fe46049251416c7506a36b"", ""de..."
4783,185465,"[{""id"": 18, ""name"": ""Drama""}]",[],Manito,"Fifteen years ago, their Washington Heights ne...","[{""cast_id"": 1, ""character"": ""Junior Moreno"", ...","[{""credit_id"": ""54931bbf925141090e001d32"", ""de..."
4784,38780,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...","[{""id"": 10022, ""name"": ""rampage""}, {""id"": 1454...",Rampage,The boredom of small town life is eating Bill ...,"[{""cast_id"": 1, ""character"": ""Bill Williamson""...","[{""credit_id"": ""52fe46df9251416c91062979"", ""de..."
4785,14022,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 305, ""name"": ""moon""}, {""id"": 490, ""nam...",Slacker,"Presents a day in the life in Austin, Texas am...","[{""cast_id"": 1, ""character"": ""Should Have Stay...","[{""credit_id"": ""52fe45c49251416c75061c17"", ""de..."
4786,366967,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",[],Dutch Kills,A desperate ex-con is forced to gather his old...,"[{""cast_id"": 4, ""character"": ""Val"", ""credit_id...","[{""credit_id"": ""563d13ec9251414c70007d5e"", ""de..."
4787,255266,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 13043, ""name"": ""dating""}, {""id"": 15160...",Dry Spell,Sasha tries to get her soon-to-be ex husband K...,"[{""cast_id"": 4, ""character"": ""Sasha"", ""credit_...","[{""credit_id"": ""52fe4ee39251416c911412e7"", ""de..."
4788,17345,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10751, ""n...","[{""id"": 186, ""name"": ""christianity""}, {""id"": 4...",Flywheel,"Jay Austin wants to sell you a used car, but w...","[{""cast_id"": 1, ""character"": ""Jay"", ""credit_id...","[{""credit_id"": ""52fe471e9251416c7508e579"", ""de..."
4789,226458,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...","[{""id"": 9712, ""name"": ""possession""}]",Backmask,"During an all-night, drug-fueled party at an a...","[{""cast_id"": 3, ""character"": ""Father Conway"", ...","[{""credit_id"": ""554c8351c3a3685e500041f5"", ""de..."
4790,24055,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...","[{""id"": 171993, ""name"": ""mumblecore""}]",The Puffy Chair,Josh's life is pretty much in the toilet. He's...,"[{""cast_id"": 4, ""character"": ""Josh"", ""credit_i...","[{""credit_id"": ""52fe447fc3a368484e026881"", ""de..."
4791,287625,"[{""id"": 18, ""name"": ""Drama""}]",[],Stories of Our Lives,Created by the members of a Nairobi-based arts...,"[{""cast_id"": 8, ""character"": """", ""credit_id"": ...","[{""credit_id"": ""549e790a9251414d27003096"", ""de..."
4792,44990,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 10183, ""name"": ""independent film""}]",Breaking Upwards,"'Breaking Upwards' explores a young, real-life...","[{""cast_id"": 1, ""character"": ""Zoe"", ""credit_id...","[{""credit_id"": ""572239efc3a368712a0007db"", ""de..."
4793,86304,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 9715, ""name"": ""superhero""}]",All Superheroes Must Die,"Masked vigilantes Charge (Jason Trost), Cutthr...","[{""cast_id"": 1, ""character"": ""Charge / John"", ...","[{""credit_id"": ""52fe497f9251416c910af3d1"", ""de..."
4794,692,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...","[{""id"": 237, ""name"": ""gay""}, {""id"": 900, ""name...",Pink Flamingos,Notorious Baltimore criminal and underground f...,"[{""cast_id"": 8, ""character"": ""Divine / Babs Jo...","[{""credit_id"": ""52fe426bc3a36847f801d203"", ""de..."
4795,39851,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 6782, ""name"": ""addiction""}, {""id"": 155...",Clean,"After losing her husband to a heroin overdose,...","[{""cast_id"": 1, ""character"": ""Emily Wang"", ""cr...","[{""credit_id"": ""52fe47369251416c9106db9b"", ""de..."
4796,13898,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",[],The Circle,Various women struggle to function in the oppr...,"[{""cast_id"": 3, ""character"": ""Nargess"", ""credi...","[{""credit_id"": ""52fe45b09251416c7505f189"", ""de..."
4797,157185,"[{""id"": 27, ""name"": ""Horror""}]","[{""id"": 14903, ""name"": ""home invasion""}]",Tin Can Man,Recently dumped by his girlfirend for another ...,"[{""cast_id"": 1, ""character"": ""Dave"", ""credit_i...","[{""credit_id"": ""54c7851b925141679100372a"", ""de..."
4798,36095,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...","[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",Cure,A wave of gruesome murders is sweeping Tokyo. ...,"[{""cast_id"": 3, ""character"": ""Kenichi Takabe"",...","[{""credit_id"": ""52fe45cc9251416c9103eb7b"", ""de..."
4799,182291,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 718, ""name"": ""confession""}, {""id"": 100...",On The Downlow,Isaac and Angel are two young Latinos involved...,"[{""cast_id"": 1, ""character"": ""Isaac"", ""credit_...","[{""credit_id"": ""548c416392514122ef00197d"", ""de..."
4800,286939,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",[],Sanctuary: Quite a Conundrum,"It should have been just a normal day of sex, ...","[{""cast_id"": 3, ""character"": ""Mimi"", ""credit_i...","[{""credit_id"": ""545f8107c3a3686cbb0041fd"", ""de..."
4801,124606,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 10726, ""name"": ""gang""}, {""id"": 33928, ...",Bang,A young woman in L.A. is having a bad day: she...,"[{""cast_id"": 2, ""character"": ""The Girl"", ""cred...","[{""credit_id"": ""52fe4ab0c3a368484e161add"", ""de..."
4802,14337,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 1448, ""name"": ""distrust""}, {""id"": 2101...",Primer,Friends/fledgling entrepreneurs invent a devic...,"[{""cast_id"": 1, ""character"": ""Aaron"", ""credit_...","[{""credit_id"": ""52fe45e79251416c75066791"", ""de..."
4803,67238,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 53, ...",[],Cavite,"Adam, a security guard, travels from Californi...",[],"[{""credit_id"": ""52fe475dc3a368484e0c319f"", ""de..."
4804,9367,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,[],[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
id          4809 non-null int64
genres      4809 non-null object
keywords    4809 non-null object
title       4809 non-null object
overview    4806 non-null object
cast        4809 non-null object
crew        4809 non-null object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [14]:
movies.isnull().sum()

id          0
genres      0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [16]:
movies.shape

(4806, 7)

In [17]:
movies.duplicated().sum()

0

In [18]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
import ast

In [20]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [22]:
movies.head()

,id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
def convert2(obj):
    counter = 0
    L = []
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [25]:
movies.head()

,id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L